# Generated by Django 4.1.3 on 2023-08-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('company', models.CharField(max_length=150)),
                ('manufacturedDate', models.DateField()),
                ('expiryDate', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('photoId', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
